import React from 'react'
import { NavLink } from 'react-router-dom/cjs/react-router-dom'

export default function MucLuc() {
  return (
    <div className="w-100 h-auto">
    <div className="container-xl pt-4">
      <div className="rounded-3 bg-white h-auto w-100 mt-4 clearfix">
        <p className="m-0 muclucnganhnghe">
          <i className="fa fa-solid fa-magnifying-glass" /> MỤC LỤC NGÀNH
          NGHỀ
        </p>
        <div className="p-4 m-0 text-center mucluc_pc">
          <span className="pe-3 fw-semibold">Tìm ngành theo</span>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/A"
          >
            A
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/B"
          >
            B
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/C"
          >
            C
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/D"
          >
            D
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/E"
          >
            E
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/F"
          >
            F
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/G"
          >
            G
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/H"
          >
            H
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/I"
          >
            I
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/K"
          >
            K
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/L"
          >
            L
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/M"
          >
            M
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/N"
          >
            N
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/O"
          >
            O
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/P"
          >
            P
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Q"
          >
            Q
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/R"
          >
            R
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/S"
          >
            S
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/T"
          >
            T
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/U"
          >
            U
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/V"
          >
            V
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/W"
          >
            W
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/X"
          >
            X
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Y"
          >
            Y
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Z"
          >
            Z
          </a>
        </div>
        <div className="p-4 m-0 text-center mucluc_mobile">
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/A"
          >
            A
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/B"
          >
            B
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/C"
          >
            C
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/D"
          >
            D
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/E"
          >
            E
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/F"
          >
            F
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/G"
          >
            G
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/H"
          >
            H
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/I"
          >
            I
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/K"
          >
            K
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/L"
          >
            L
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/M"
          >
            M
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/N"
          >
            N
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/O"
          >
            O
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/P"
          >
            P
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Q"
          >
            Q
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/R"
          >
            R
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/S"
          >
            S
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/T"
          >
            T
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/U"
          >
            U
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/V"
          >
            V
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/W"
          >
            W
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/X"
          >
            X
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Y"
          >
            Y
          </a>
          <a
            id="muclucnganhnghe_link"
            href="https://trangvangvietnam.com/findex/Z"
          >
            Z
          </a>
        </div>
      </div>
      <div className="rounded-3 p-3 pb-4 border h-auto w-100 mt-5 mb-5">
        <div className="foot_signup1">Bạn là doanh nghiệp?</div>
        <div className="foot_signup2">
          Đăng ký Trang vàng là cách đơn giản và hiệu quả để bạn quảng bá,
          bán hàng, giữ và phát triển thị phần !<br />
          <span className="text-black-50">
            <small>
              Hãy gọi hoặc gửi Zalo đến <strong>0934.498.168</strong> (gửi
              Zalo)/ <strong>0912.005.564</strong> (gửi Zalo) để được tư vấn
              và hỗ trợ.
            </small>
          </span>
        </div>
        <div className="foot_signup3">
          <button className="border-0 rounded-2 p-1 ps-3 pe-3 buttom_bg_footer_signup text-white">
          <NavLink to="/signup" style={{background:'none'}} >
              Đăng ký miễn phí !
          </NavLink>
          </button>
        </div>
        <p className="m-0 p-0 mb-1 clearfix" />
      </div>
      <p className="m-0 clearfix" />
    </div>
  </div>
  )
}
