export   const ListCareer = [
    {id:1,name:'An ninh - Bảo vệ'},
    {id:2,name:'Bao bì'},
    {id:3,name:'Bảo hộ lao động'},
    {id:4,name:'Cao su'},
    {id:5,name:'Cơ khí'},
    {id:6,name:'Thiết bị điện'},
    {id:7,name:'Điện lạnh'},
    {id:8,name:'Đồ gia dụng'},
    {id:9,name:'Doanh nghiệp cần dùng'},
    {id:10,name:'Du lịch'},
    {id:11,name:'Vận tải - giao nhận'},
    {id:12,name:'Giấy - sản phẩm giấy'},
    {id:13,name:'Đồ gỗ'},
    {id:14,name:'Hóa chất'},
    {id:15,name:'May mặc'},
    {id:16,name:'Máy móc'},
    {id:17,name:'Môi trường'},
    {id:18,name:'Nhựa - Sản phẩm nhựa'},
    {id:19,name:'Nội Thất'},
    {id:20,name:'Nông nghiệp'},
    {id:21,name:'Ô tô - xe máy'},
    {id:22,name:'Quà tặng'},
    {id:23,name:'Quảng cáo'},
    {id:24,name:'Y tế - Thiết bị Y tế'},
    {id:25,name:'Thép - Inox'},
    {id:26,name:'Thủ công mỹ nghệ'},
    {id:27,name:'Thực phẩm - đồ uống'},
    {id:28,name:'Văn Phòng phẩm'},
    {id:29,name:'Vật liệu xây dựng'},
    {id:30,name:'Viễn thông'},
    {id:31,name:'Xây dựng'},
    {id:32,name:'Xuất nhập khẩu'},
  ]
