export const ListCity = [
    'Hà Nội',
    'Hồ Chí Minh',
    'Đà Nẵng',
    'Hải Phòng',
    'Huế',
    'Hải Dương',
    'Nam Định',
    'Vũng Tàu',
    'Nha Trang',
    'Cần Thơ',
    'Bắc Ninh',
    'Bắc Giang',
    'Quảng Ninh',
    'Lào Cai',
    'Điện Biên',
    'Lạng Sơn',
    'Thái Bình',
    'Vĩnh Phúc',
    'Hà Tĩnh',
    'Nghệ An',
    'Quảng Bình',
    'Quảng Trị',
    'Thừa Thiên Huế',
    'Quảng Ngãi',
    'Bình Định',
    'Phú Yên',
    'Kon Tum',
    'Gia Lai',
    'Đắk Lắk',
    'Đắk Nông',
    'Lâm Đồng',
    'Bình Thuận',
    'Khánh Hòa',
    'Bà Rịa - Vũng Tàu',
    'Long An',
    'Tiền Giang',
    'Bến Tre',
    'Trà Vinh',
    'Vĩnh Long',
    'Đồng Tháp',
    'An Giang',
    'Kiên Giang',
    'Cà Mau',
    'Sóc Trăng',
    'Bạc Liêu',
    'Hậu Giang',
    'Yên Bái',
    'Tuyên Quang',
    'Quảng Nam',
    'Hà Nam',
    'Thái Nguyên',
    'Bình Phước',
    'Tây Ninh',
    'Bình Dương',
    'Đồng Nai',
    'Sài Gòn',
  ];
  